import Header from '@/components/Header';
import './globals.css';
import { Nunito, Playfair_Display, Inter } from 'next/font/google';
import { cn } from '@/lib/utils';

const playFair = Playfair_Display({ subsets: ['latin'] });
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={cn(
        'bg-gray-910 shadow-white shadow-md text-gray-100 antialiased',
        inter.className
      )}
    >
      <body className='relative min-h-screen flex flex-col antialiased'>
        <Header />
        <div className="flex-grow flex justify-center items-center">
          {children}
        </div>
      </body>
    </html>
  );
}
